### ISSUE TITLE
Using with Monolog results in no mail?

### ISSUE THREAD

**Issue by patrickbussmann** [Nyholm/bref-symfony-messenger#60]
Maybe some of you already know this "issue".
I'm wondering why I got no error message of the messenger worker.
But in the log of CloudWatch I can see all of this.

**My `monolog.yaml` looks like:**

```yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_http_codes: [404, 405, 409]
            buffer_size: 50
        grouped:
            type:    group
            members: [nested, deduplicated]
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'info@example.org'
            to_email:   ['info@example.org']
            subject:    'Error! %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
        nested:
            type: stream
            path: "php://stderr"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
```

**And the exception is:**

```
{
    "errorType": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
    "errorMessage": "Handling \"App\\Message\\PaymentCapturedMessage\" failed: Call to undefined method",
    "stack": [
        "#0 /var/task/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(74): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()",
        "#1 /var/task/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()",
        "#2 /var/task/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()",
        "#3 /var/task/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(48): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()",
        "#4 /var/task/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()",
        "#5 /var/task/vendor/symfony/messenger/MessageBus.php(77): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()",
        "#6 /var/task/vendor/bref/symfony-messenger/src/Service/SimpleBusDriver.php(24): Symfony\\Component\\Messenger\\MessageBus->dispatch()",
        "#7 /var/task/vendor/bref/symfony-messenger/src/Service/Sqs/SqsConsumer.php(58): Bref\\Symfony\\Messenger\\Service\\SimpleBusDriver->putEnvelopeOnBus()",
        "#8 /var/task/vendor/bref/bref/src/Event/Sqs/SqsHandler.php(24): Bref\\Symfony\\Messenger\\Service\\Sqs\\SqsConsumer->handleSqs()",
        "#9 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(29): Bref\\Event\\Sqs\\SqsHandler->handle()",
        "#10 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(91): Bref\\Runtime\\Invoker->invoke()",
        "#11 /opt/bref/bootstrap.php(43): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
        "#12 {main}"
    ]
}
```
